### ISSUE TITLE
How to send message to QGC or other UAVs?

### ISSUE THREAD

**Issue by weiminshen99** [dronekit/dronekit-python#812] opened 2018-04-01 16:23 UTC
Hi, Everyone,

I have been using dronekit-python happily, but recently there is a need to send mavlink messages from my dronekit to QGC or UAVs other than the one that is connected with my dronekit. For example, two UAVs and QGC are connected as follows:

Dronekit<==>UAV1  <--- mavlink ---->  UAV2 <--- mavlink ---> QGC 

Could someone tell me how to send a message from Dronekit to UAV2 or GGC?  I have been trying to modify the code of dronekit-python to do this but without any success. Any help would be greatly appreciated.  Thanks!

**Comment by pietrodn** [comment] 2018-04-01 18:47
I managed to forward the MAVLink messages coming from an UAV connected to a serial port through DroneKit to QGroundControl.

UAV (PX4) <==== (serial) ====> DroneKit <==== (MAVLink UDP stream) ====> QGroundControl

The code to do so is already present in DroneKit. Look into the [`mavlink.py`](https://github.com/dronekit/dronekit-python/blob/master/dronekit/mavlink.py) file for the `mavudpin_multi` class and for the `MAVConnection.pipe()` method.

The code I used is:

```python
vehicle = dronekit.connect('/dev/ttyS0')  # ... and other connection options
udp_conn = MAVConnection('udpin:0.0.0.0:15667', source_system=1)
vehicle._handler.pipe(udp_conn)
udp_conn.master.mav.srcComponent = 1  # needed to make QGroundControl work!
udp_conn.start()
```

This code starts a listener on UDP port 15667 which automatically establishes the necessary connections with clients. All MAVLink messages coming from the vehicle are forwarded on the UDP clients, and all the messages coming from the UDP clients are forwarded to the client.

To make the forwarding work I had to alter the source component ID.

Then I configured QGroundControl to contact the host running DroneKit via UDP on port 15667. QGroundControl itself should listen on another port.
Here's an example configuration:

![QGroundControl configuration](https://i.imgur.com/5nJsfYD.png)

**Comment by weiminshen99** [comment] 2018-04-02 00:50
@pietrodn ,

Thanks for your nice and quick post! I immediately tried it but not yet get it working. Here is what I did to send PING messages from my dronekit to QGC:

====================
        self.vehicle = connect('127.0.0.1:14540', 57600) # wait_ready=True, heartbeat_timeout=60
        udp_conn = MAVConnection('udpin:127.0.0.1:15667', source_system=1)
        self.vehicle._handler.pipe(udp_conn)
        udp_conn.master.mav.srcComponent = 1  # needed to make QGroundControl work!
        udp_conn.start()
        self.vehicle.add_message_listener('PING', listen_msg_src)  # listen on PING msg
        self.msg1 = self.vehicle.message_factory.ping_encode(1000,1,255,1) # prepare a PING to QGC
        self.vehicle.send_mavlink(self.msg1)    # send the PING to QGC
====================

On QGC, I connected, as you shown, 127.0.0.1:15667. I was hoping to see the PING messages at QGC, but they did not show up. Also, I tried the same thing to PING another UAV with target_system=2, and no luck.

Could you please let me know what I did not do right? In addition, could you please post your minimal but complete code so that we can try exactly what you did? For example, what messages did you send? What are the results you see at QGC? Other small differences include: you used 'udpin:0.0.0.0:15667', I used 'udpin:127.0.0.1:15667'. Yours is connect('/dev/ttyS0'), mine connect('127.0.0.1:14540') for a PX4 SITL. I don't know if these make any differences. Have you tried it on a PX4 SITL? Thanks for your help!

**Comment by pietrodn** [comment] 2018-04-02 06:16
I tried exclusively on the PX4 firmware.

For the “udpin” connection string, the IP tells on which interfaces DroneKit should be listening for incoming connections. 0.0.0.0 means “all interfaces”, so I recommend using that until you get the forwarding to work.

Also, check if you have a firewall blocking some ports.

I didn’t need to manually send any message: I clicked on “connect” on QGC and the software displayed me the full status of the drone (battery, sensors, parameters, etc.)

Are QGC and PX4 running on the same host?

**Comment by pietrodn** [comment] 2018-04-02 06:18
And yes, I tried both on a real UAV and on a PX4 SITL. On the SITL, however, I had to disable the automatic listening on UDP port 14540 on QGC, otherwise QGC will try to connect directly to the SITL and not to the forwarded connection.

**Comment by pietrodn** [comment] 2018-04-02 06:20
Oh, and don’t use 14540 or 14550 as a listening port on QGC... use something random, not related to the SITL. Otherwise it will complain that the port is already bound by another application.

**Comment by weiminshen99** [comment] 2018-04-02 19:22
Thanks for your detailed replies! I am almost there but have one more question. I have my QGC connected to 15667 first, but when I started my dronekit after that, dronekit complains that 15667 is already in use. But if I first connect dronekit on 15667, then QGC will complain that 15667 is already in use when I clink connect there. What did I miss?

**Comment by pietrodn** [comment] 2018-04-02 22:26
Probably you set 15667 as the "listening port" in QGC. Try to use another port. Otherwise, there is another process running...

**Comment by pietrodn** [comment] 2018-04-03 05:50
For the formatting thing, GitHub supports a simple markup language called “GitHub flavored Markdown”. Google it :-)

To avoid the fix_targets correction, I’m afraid you’ll have to monkey-patch the MAVConnection class:

    def my_new_fix_targets(self, message):
        # your code
    
    udp_conn.fix_targets = my_new_fix_targets

Where your new method may as well be a no-op.

Or, if you always want the same target to be set, you can set the udp_conn.target_system attribute so that fix_target will write what you want.

**Comment by weiminshen99** [comment] 2018-04-03 17:36
Great suggestions and it is working! The code that modifies udp_conn.fix_targets and uses udp_conn.master.mav.send to send messages are here:
         
           def my_new_fix_targets(message):
                         pass
           udp_conn.fix_targets = my_new_fix_targets
           self.msg = self.vehicle.message_factory.statustext_encode(1,'Hello')
           udp_conn.master.mav.send(self.msg)
           self.msg = self.vehicle.message_factory.ping_encode(4567,8,255,1)
           udp_conn.master.mav.send(self.msg)

The results: you can hear QGC saying "Hello" and see the PING messages in QGC's Mavlink Inspector.
The only thing strange about this is that the ID 255 does not seem to be relevant. You can change it to any ID and QGC still receives the PING message. Is that normal?

**Comment by pietrodn** [comment] 2018-04-03 17:45
Does QGC also reply to the ping when the ID is incorrect?

**Comment by weiminshen99** [comment] 2018-04-03 18:17
QGC does not seem to reply to any ping messages no matter if the ID is correct or not. My vehicle is "listening" to PING messages as follows, so if there is a reply PING, it should be heard:
                       self.vehicle.add_message_listener('PING',       listen_msg_src)
Maybe the current QGC has not implemented the PING protocol yet. (I know PX4 does not).

**Comment by pietrodn** [comment] 2018-04-03 18:34
[Here](https://github.com/mavlink/qgroundcontrol/issues/2627) I see a long-ish discussion on QGC's PING implementation. Didn't read it all but maybe it could be of interest. Good luck! :-)

**Comment by weiminshen99** [comment] 2018-04-04 04:55
Hi, @pietrodn ,
Sorry to bother you for another dumb question. For the following two configurations, CONFIG#A works, but I don't know how to make Config#B work.

CONFIG#A: PX4#1<=>DroneKit#1(15667) <=== (MAVLink UDP stream) ===> QGC

CONFIG#B: PX4#1<=>DroneKit#1(15667) <=== (MAVLink UDP stream) ===> DroneKit#2<=>PX4#2

In CONFIG#A, as you suggested, I could target QGC to the udp port (15667) opened by DroneKit#1. But in CONFIG#B, I don't know how to make DroneKit#2 connect to 15667. I tried connect('127.0.0.1:15667', 921600, wait_ready=True) from DroneKit#2, but it does not work.
Please help. Thanks so much!

**Comment by weiminshen99** [comment] 2018-04-04 04:58
Please ignore the links in my last message, they were not intended. Please read them as they are.

**Comment by weiminshen99** [comment] 2018-04-05 22:30
Thanks for your suggestion and I have tried the following code for many times. All is fine except line 2.2 runs into an error "Address already in use". Can you see any obvious mistakes? I have a question how a udp connection is made. For example, between two parties (say d1 and d2 below), if d1 is already listening on port 15667, should d2 just call mavudp and connect to 15667 and be done with it? Why it complains "address already in use"?

### On DroneKit_1 (d1):
1.1. vehicle1 = dronekit.connect('ip_for_PX4_1',source_system=1)  # connect d1 to PX4_1
1.2. udp_pipe_to_d2 = MAVConnection('udpin:0.0.0.0:15667', source_system=1)
1.3. vehicle1._handler.pipe(udp_pipe_to_d2)
1.4. udp_pipe_to_d2.master.mav.srcComponent = 1
1.5. udp_pipe_to_d2.start() # start the pipe to DroneKit_2

### On DroneKit_2 (d2):
2.1. vehicle2 = dronekit.connect('ip_for_PX4_2',source_system=2)  # connect d2 to PX4_2
2.2. udpconn_to_d1 = mavutil.mavudp(0.0.0.0:15667, source_system=2, source_component=1) # connect d1

Line 2.2. runs into an error "Address already in use". Did I use the function mavudp correctly? Please help!

**Comment by weiminshen99** [comment] 2018-04-06 00:26
d1 and d2 are now connected, but d2 does not seem to receive any messages sent from d1.  Suggestions?

**Comment by weiminshen99** [comment] 2018-04-06 00:31
Sorry, they still do not connect when the same port is used. Same error “Address already in use”.

**Comment by weiminshen99** [comment] 2018-04-06 02:30
Hi, @pietrodn, 
Finally, it is working!!!  Here is the good Line 2.2:
2.2. udpconn_to_d1 = connect(udpout:0.0.0.0:15667, source_system=2)
After this, d2 can listen to the PING messages sent from d1 on udpconn_to_d1 as follows:
2.3. udpconn_to_d1.add_message_listener('PING', listen_msg_src)

Putting all together, I now have the following configuration working. Thank you!!!
![image](https://user-images.githubusercontent.com/24813239/38400928-77780d74-3907-11e8-89c7-1bf0ea4a8c36.png)

**Comment by pietrodn** [comment] 2018-04-06 11:11
I’m glad it is working! :-)
The “address already in use” message means that you are trying to bind two sockets on the same port on the same host, namely two UDP input connections.

**Comment by weiminshen99** [comment] 2018-04-06 17:49
Thank you! It was quite tricky to find out that the "udpout" was the right option for the connect function. I had to dig deep into the dronekit code. Do you know if there is a way to make it more obvious for people to use in the future?

**Comment by pietrodn** [comment] 2018-04-06 17:50
You may contribute to the documentation! :-) It is in the "docs" directory.

**Comment by weiminshen99** [comment] 2018-04-06 23:12
I will be glad to. Any suggestion for where and how to proceed?

**Comment by pietrodn** [comment] 2018-04-07 16:06
http://python.dronekit.io/contributing/contributions_documentation.html

**Comment by AsternA** [comment] 2018-06-03 11:17
Hey @weiminshen99 @weiminshen99 I have read all of the conversations and am hoping you can help.

This is the setup I am trying to achieve:

![rpiflowchart](https://user-images.githubusercontent.com/35406040/40885965-81778e8a-6738-11e8-8f3e-5e444fa34abb.PNG)

notice that the way to the liner servo is unidirectional but it is using the vehicle parameters that are constantly being updated and sent to the GCS. 

So, I somehow need to divide the information, inside the RPi, coming from the pixhawk into two separate paths - one is to the GCS and the other to "loopback" into the RPi so that the parameters are the updated ones.

So now the question, would you recommend following your instructions and will it solve my issue?

Thanks

**Comment by AsternA** [comment] 2018-06-03 12:51
#677 last comment full information

**Comment by weiminshen99** [comment] 2018-06-08 03:40
@AsternA Congratulations to you for finding the solution you wanted!

**Comment by AfshinMr** [comment] 2018-11-05 18:07
@pietrodn Hi pietro,
I was reading your discussion and it is very similar to what I need to do ! I want to use the Dronekit as a proxy between the QGC and the Autopilot. I need to receive the waypoints from the QGC by the Dronekit, then modify the waypoints and the forward the new waypoints to the autopilot. The construction is like yours:
UAV (Autopilot) <==== (serial) ====> DroneKit <==== (MAVLink UDP stream) ====> QGroundControl
First I started to establish the connection between the QGC and the Dronekit, without any Autopilot. In fact from the QGC point of view, the Dronekit is the autopilot. I followed all the same as you explained but still the QGC does not recognize the Dronekit.
This is what I configured from QGC side:
![image](https://user-images.githubusercontent.com/42065599/48017175-ea91c600-e12d-11e8-9c78-8970d46a1bb6.png)

**Comment by pietrodn** [comment] 2018-11-05 18:11
I think that the problem is that you're trying to initialize a `MAVConnection` without a `Vehicle`.
The `MAVConnection` object does not send any message by itself, not even heartbeats. So, QGC won't connect.

**Comment by AfshinMr** [comment] 2018-11-05 18:15
I updated my question.
Ok, so what do you think I need to do in order to first establish the connection between QGC and Dronekit ? (QGC see the Dronekit as Autopilot)

Or is it needed that I do that? or directly establish the two connections? If I do so, Is it possible to modify the waypoints received from QGC?

**Comment by pietrodn** [comment] 2018-11-05 18:18
I think that as a first step you should connect DroneKit to the autopilot and then setup the relay to QGC.
Honestly I don't know how to edit the messages in-flight, I'm only using this method to perform manual setup on my DroneKit-controlled drone.

**Comment by AfshinMr** [comment] 2018-11-05 18:29
@pietrodn  when I connect the Dronekit and the copter (I use dronekit-sitl copter), the connection will be established and I can upload the waypoints, but I was afraid that maybe the QGC is directly sending the waypoints to the Autopilot and there is no relay between ! because I thought that I have to use a command from the Dronekit to upload the waypoints to the autopilot, but now when I upload the waypoints from QGC, the autopilot also receives the waypoints and mission can be started ! in fact I have no control to forward or not to forward the received waypoints from the QGC to the autopilot. What do you think? is there any way to manage this issue? any idea?

**Comment by pietrodn** [comment] 2018-11-05 18:42
Yes, that's precisely the point: in my setup QGC sends the messages directly to the autopilot, in the sense that the system ID in the MAVLink messages is the autopilot's one.

Maybe you can play with the `forward_message` decorator (see [here](https://github.com/dronekit/dronekit-python/blob/master/dronekit/mavlink.py#L306)) to manipulate the messages coming and arriving from QGC. But again, I've never attempted it, so I'm unable to give you detailed instructions. :-)

**Comment by AfshinMr** [comment] 2018-11-06 10:16
Thank you very much for your answers :-)
by the way, do you have any other idea, how to create a proxy, which receives the data from QGC and then after modification, forwards them to the Autopilot? what about Pymavlink? have you ever had any experiences?

**Comment by AfshinMr** [comment] 2018-11-08 13:00
Hi @pietrodn ,
As, I could not find a way to manipulate the messages coming from the QGC by dronekit, I am now trying to create the same thing with Pymavlink library. It is possible to receive and manipulate the messages with pymavlink library. The only problem is that now I can connect to the vehicle and also can connect to the QGC from my proxy, but the QGC does not recognize the vehicle to be able to send the messages. I receive heartbeat from both the vehicle and the QGC. 
I think I need the same thing that you used for dronekit 
`vehicle._handler.pipe(udp_conn)
udp_conn.master.mav.srcComponent = 1  # needed to make QGroundControl work!`
but working in pymavlink. Do you have any idea how can I solve it?

**Comment by AfshinMr** [comment] 2018-11-20 13:42
Hi @pietrodn 
I created the proxy as following:
I have created the interfaces as you described to me in Python. Here is the code:

          `gcs_conn = mavutil.mavlink_connection('tcpin:localhost:15795')
           gcs_conn.wait_heartbeat()
           print("Heartbeat from system (system %u component %u)" % (gcs_conn.target_system, gcs_conn.target_system))
           vehicle = mavutil.mavlink_connection('tcp:localhost:5760')
           vehicle.wait_heartbeat() # recieving heartbeat from the vehicle
           print("Heartbeat from system (system %u component %u)" % (vehicle.target_system, vehicle.target_system))
           while True:
                     gcs_msg = gcs_conn.recv_match()
                     if gcs_msg == None:
                            pass
                     else:
                            vehicle.mav.send(gcs_msg)
                            print(gcs_msg)

                     vcl_msg = vehicle.recv_match()
                     if vcl_msg == None:
                            pass
                     else:
                            gcs_conn.mav.send(vcl_msg)
                            print(vcl_msg)
`
First I just want to receive and forward the messages ! But it still does not work and when I run the code I get this:
![selection_005](https://user-images.githubusercontent.com/42065599/48777289-7f6df500-ecd2-11e8-8a83-174ac1865ec5.png)
Can you help me here?

**Comment by pietrodn** [comment] 2018-11-20 18:47
I think you found a bug in pymavlink! Please do the `print(vcl_msg)` **before** the send so we can understand which kind of strange message we are dealing with...

**Comment by AfshinMr** [comment] 2018-11-21 10:36
@pietrodn Thank you for your response. 
I put the the `print(vcl_msg)` before the send and I received a lot of **None** among the messages that you see above!
you sure that I am using the right command to send the messages ?
How can I find that the messages I am sending, will be received in the destination (vehicle or QGC)?
What do you think if I send the received messages one by one? I mean e.g. I receive from the vehicle are as following:
![selection_006](https://user-images.githubusercontent.com/42065599/48835826-6c662e00-ed81-11e8-8ea9-b35ba469ae0b.png)
Then I send them like:
`vehicle.mav.gps_raw_int_send(time_usec = gcs_conn.messages['HOME'].time_usec, fix_type = gcs_conn.messages['HOME'].fix_type, lat = gcs_conn.messages['HOME'].lat, lon = gcs_conn.messages['HOME'].lon, alt = gcs_conn.messages['HOME'].lat, eph = gcs_conn.messages['HOME'].eph, epv = gcs_conn.messages['HOME'].epv, vel = gcs_conn.messages['HOME'].vel, cog = gcs_conn.messages['HOME'].cog, satellites_visible = gcs_conn.messages['HOME'].satellites_visible)
        `
to send the HOME messages receiving from the vehicle to the QGC.
what do you think?

**Comment by pietrodn** [comment] 2018-11-21 11:18
> I put the the print(vcl_msg) before the send and I received a lot of None among the messages that you see above!

Are you sure? How can they be None, if you explicitly check for it before?

> How can I find that the messages I am sending, will be received in the destination (vehicle or QGC)?

You need to check on the receiving side :-)

> What do you think if I send the received messages one by one?

Not a good idea, it's better to use a generic send method.

**Comment by pietrodn** [comment] 2018-11-21 12:38
> Yes it is strange but there are a lot of None among the messages that I you see in the first screenshot. Thats the reason I put a if statement to pass if the message is None. vcl_msg is the message coming from the vehicle and is strange that the vehicle is sending None!
> 
It’s fine that recv_match returns None, since it’s a non-blocking function: if there are no bytes on the receive buffer, the method doesn’t wait and returns None.
So you have to check but it isn’t a problem.

**Comment by AfshinMr** [comment] 2018-11-21 13:10
@pietrodn so what was strange when I said it is returning a lot of None? I am confused :-)

By the way,
Any idea, how can I make the QGC to recognize the vehicle? I see that the connections are established and data are transferring ! (before the error occurs) ! But why the QGC does not recognize the vehicle?

**Comment by pietrodn** [comment] 2018-11-21 17:00
> @pietrodn so what was strange when I said it is returning a lot of None? I am confused :-)

Sorry, I didn't make myself clear. Print the message *inside* the `if` block, so that you can see which message makes the application crash.

**Comment by AfshinMr** [comment] 2018-11-21 17:43
@pietrodn  Sorry but I do not get where you mean! previously (first screen shot) it was inside the `if` statement that the error is clear in the screen shot. Then I put it outside and the None messages also were included. Now I don't know where else exactly you mean! Can you show me in the code?

**Comment by pietrodn** [comment] 2018-11-21 22:48
Ok. You did:
```python
vcl_msg = vehicle.recv_match()
if vcl_msg == None:
    pass
else:
    gcs_conn.mav.send(vcl_msg)
    print(vcl_msg)
```

Your program crashed on `send()`, but since the `print()` is *after* the `send()`, I don't know which message caused the program to crash.
My suggestion is to do:

```python
vcl_msg = vehicle.recv_match()
if vcl_msg == None:
    pass
else:
    print(vcl_msg)
    gcs_conn.mav.send(vcl_msg)
```

So that the last printed line shows the problematic message.

**Comment by AfshinMr** [comment] 2018-11-22 10:17
@pietrodn  I got  it.
Here it is:
![selection_008](https://user-images.githubusercontent.com/42065599/48896492-085a6d00-ee48-11e8-9858-96ea35491412.png)
There is a 'BAD_DATA' before the program crashes.  I filter the bad data ?

**Comment by AfshinMr** [comment] 2018-11-22 10:57
@pietrodn I change the if condition to the following:
`

        if vcl_msg == None or isinstance(vcl_msg, pymavlink.dialects.v10.ardupilotmega.MAVLink_bad_data):

                  pass

        else:
        
                  print(vcl_msg)

                  gcs_conn.mav.send(vcl_msg)`

and I got the following without any crash:
![selection_009](https://user-images.githubusercontent.com/42065599/48898645-9127d780-ee4d-11e8-96a5-d5cd3a8d1a85.png)

But the problem is that the QGC does not recognize the vehicle and so nothing happens! just the heartbeats !

**Comment by hamishwillee** [comment] 2018-11-22 11:15
It suspect that QGC only supports PX4/ArduPilot for some things and won't recognise systems that advertise as something else. It may also require that your system implement some minimal set of autpilot protocols - e.g. parameter protocol.

**Comment by AfshinMr** [comment] 2018-11-22 14:22
Thank you @hamishwillee  for your comment. In my application, I am trying just to forward whatever I receive from the QGC to the vehicle and vise versa. So, When the QGC is receiving all the messages that it receives in the direct connection, why it should not recognize the vehicle?!
What do you mean that my system require to implement some minimal set of parameters? can you explain more? what do you suggest to do then?

**Comment by AfshinMr** [comment] 2018-11-22 17:13
@pietrodn , @hamishwillee  I created a direct connection between the vehicle and QGC and investigated which messages are being transferred. Here it is:
![selection_012](https://user-images.githubusercontent.com/42065599/48916333-13ca8a00-ee82-11e8-8f4c-6c6ac034d039.png)
But when I put the proxy to receive and send the messages, these are the transferred messages:
![selection_011](https://user-images.githubusercontent.com/42065599/48916347-32308580-ee82-11e8-88f7-26ced77c5f9a.png)
Therefore, QGC is not asking for some messages! and that's the reason that it does not recognize the vehicle !
What do you think? How can I deal with this?

**Comment by pietrodn** [comment] 2018-11-22 17:48
I see that you are communicating with QGC via TCP. Try UDP instead, and check that the port is open (Wireshark, netcat...)

**Comment by hamishwillee** [comment] 2018-11-22 21:35
Yes, @pietrodn advice is good - I don't think PX4 supports TCP connections. Certainly SITL does not.

**Comment by AfshinMr** [comment] 2018-11-23 16:48
@pietrodn @hamishwillee  I replaced the communication between the proxy and QGC with UDP connection. I received the same messages as following:
![selection_013](https://user-images.githubusercontent.com/42065599/48953900-ad0fa400-ef47-11e8-880a-ee8704468451.png)
But, as I know, the UDP connection is not bidirectional ! so, I may need to create another connection for returning the messages from the proxy to the QGC ! what do you think?

**Comment by pietrodn** [comment] 2018-11-23 18:21
UDP packets have a source (port, ip) tuple and a destination (port, ip) tuple. So it is possible to "answer" to an unicast UDP datagram (think about DNS, for example).
In this case the communication is bidirectional, as you can see. QGC is sending data on UDP port 15667.

**Comment by AfshinMr** [comment] 2018-11-24 11:20
@pietrodn I understood ! 
the problem here must be the lack of some messages in `gcs_conn.messages` ! any other advises? or idea?

**Comment by AfshinMr** [comment] 2018-11-26 11:16
@pietrodn What about if I modify the `pipe` function (I mean here: `vehicle._handler.pipe(connection)),` leading not to forward messages directly ! I mean, instead of forwarding the messages, first modify them and then forwarding ! Is it possible?

**Comment by giamo152** [comment] 2021-11-15 15:59
> And yes, I tried both on a real UAV and on a PX4 SITL. On the SITL, however, I had to disable the automatic listening on UDP port 14540 on QGC, otherwise QGC will try to connect directly to the SITL and not to the forwarded connection.

Hi Pietro, how exactly did you manage this?

**Comment by pietrodn** [comment] 2021-11-15 16:18
Sorry but I don't work with drones anymore and forgot these details 😞 
I think you can achieve it by changing the connection settings in the QGC UI.

**Comment by hamishwillee** [comment] 2021-11-15 21:21
@giamo152 That's odd, since QGC listens on 14550. If you're working on PX4 I strongly recommend moving to MAVSDK as it is properly supported: https://mavsdk.mavlink.io/main/en/index.html

**Comment by giamo152** [comment] 2021-11-16 09:04
Thank you for your input @hamishwillee. I am essentially trying to spy on the communication between QGC and my PX4 (SITL).  From my little understanding, the examples of this discussion should help me do that. Am I correct? Is there even a simpler way to directly print this information exchange, either from QGC or PX4 without having to use dronekit?
Many thanks

**Comment by hamishwillee** [comment] 2021-11-16 20:42
@giamo152 In that case you should have created a separate issue rather than adding to this one. The answer to your question is "maybe".

But a better one is to use Wireshark: https://mavlink.io/en/guide/wireshark.html

**Closed** 2022-11-02 17:54 UTC
